### ISSUE TITLE
goreleaser config is out of date

### ISSUE THREAD

**Issue by ethanmdavidson** [hashicorp/packer-plugin-scaffolding#111]
The goreleaser.yml file [references a `make ci-release-docs` target](https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.goreleaser.yml#L12)  that [was removed from the GNUMakefile](https://github.com/hashicorp/packer-plugin-scaffolding/commit/ccc68a1d0a01550f2914e15cc71feea43da1bead#diff-e3445fc75aa9c3e4a60fbe5394dcce12693022018216a8fbe0000fe9952850a6). It also [references a docs.zip file](https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.goreleaser.yml#L82) that is no longer created afaict. 

Somewhat relatedly, [the release workflow uses the `--rm-dist` flag](https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.github/workflows/release.yml#L42) which has [been deprecated since 2023-01-17](https://goreleaser.com/deprecations/#-rm-dist) and now no longer works.

**Comment by nywilken** [comment]
Thanks for calling this out @ethanmdavidson I opened a PR to address the reported issues.
