### ISSUE TITLE
GitHub releases and packer usage example

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer-plugin-scaffolding#16]
For better understanding how to make a packer plugin it would be educative to have:

1. GitHub releases of this plugin.
2. A working example (e.g. in a `example` kind of directory) which could be used by `packer init`/`packer build`.
3. A github action workflow that actually uses the example to run packer to test run the plugin.

**Comment by SwampDragons** [comment]
Good call. For now, I can point you to a different toy example that has releases all set up: https://github.com/sylviamoss/packer-plugin-comment

**Comment by azr** [comment]
Do you think it would be a good idea also to have different folders, to showcase different kind of plugins:

```
.
└── examples
    ├── components
    ├── multi-component-plugin
    └── single-component-plugin
```
