### ISSUE TITLE
❗️ Critical vulnerabilities found by Dependabot in template...

### ISSUE THREAD

**Issue by scottford-io** [hashicorp/packer-plugin-scaffolding#72]
After generating a new repo, Dependabot finds a number of CRITICAL and HIGH vulnerabilities...

![image](https://user-images.githubusercontent.com/49754039/173627195-ce80932f-cde8-4dcb-9624-ce0777065da9.png)

**Comment by nywilken** [comment]
Hi @scottford-io thanks for bubbling this up. I merged the changes for the latest Packer Plugin SDK which resolve the CVEs being reported. I created a new repo against this template to verify no new CVEs are being reported. I will close this issue once confirmed.

**Comment by nywilken** [comment]
No new dependbot alerts since creating the repo. This is good to close. Thanks again for reporting.
